 // Source code is unavailable, and was generated by the Fernflower decompiler.
package java.nio.file;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.Closeable;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.Reader;
import java.io.Writer;
import java.nio.channels.Channels;
import java.nio.channels.FileChannel;
import java.nio.channels.SeekableByteChannel;
import java.nio.charset.Charset;
import java.nio.charset.CharsetDecoder;
import java.nio.charset.CharsetEncoder;
import java.nio.file.DirectoryStream.Filter;
import java.nio.file.FileTreeWalker.Event;
import java.nio.file.Files.1;
import java.nio.file.Files.2;
import java.nio.file.Files.3;
import java.nio.file.Files.AcceptAllFilter;
import java.nio.file.Files.FileTypeDetectors;
import java.nio.file.attribute.BasicFileAttributeView;
import java.nio.file.attribute.BasicFileAttributes;
import java.nio.file.attribute.FileAttribute;
import java.nio.file.attribute.FileAttributeView;
import java.nio.file.attribute.FileOwnerAttributeView;
import java.nio.file.attribute.FileTime;
import java.nio.file.attribute.PosixFileAttributeView;
import java.nio.file.attribute.PosixFileAttributes;
import java.nio.file.attribute.PosixFilePermission;
import java.nio.file.attribute.UserPrincipal;
import java.nio.file.spi.FileSystemProvider;
import java.nio.file.spi.FileTypeDetector;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.EnumSet;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.Spliterator;
import java.util.Spliterators;
import java.util.function.BiPredicate;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;
import jdk.internal.access.JavaLangAccess;
import jdk.internal.access.SharedSecrets;
import jdk.internal.util.ArraysSupport;
import sun.nio.ch.FileChannelImpl;
import sun.nio.cs.UTF_8;
import sun.nio.fs.AbstractFileSystemProvider;

public final class Files {
   private static final int BUFFER_SIZE = 8192;
   private static final Set<OpenOption> DEFAULT_CREATE_OPTIONS;
   private static final JavaLangAccess JLA;

   private static FileSystemProvider provider(Path path) {
      return path.getFileSystem().provider();
   }

   private static Runnable asUncheckedRunnable(Closeable c) {
      return c;
   }

   public static InputStream newInputStream(Path path, OpenOption... options) throws IOException {
      return provider(path).newInputStream(path, options);
   }

   public static OutputStream newOutputStream(Path path, OpenOption... options) throws IOException {
      return provider(path).newOutputStream(path, options);
   }

   public static SeekableByteChannel newByteChannel(Path path, Set<? extends OpenOption> options, FileAttribute... attrs) throws IOException {
      return provider(path).newByteChannel(path, options, attrs);
   }

   public static SeekableByteChannel newByteChannel(Path path, OpenOption... options) throws IOException {
      Object set;
      if (options.length == 0) {
         set = Collections.emptySet();
      } else {
         set = new HashSet();
         Collections.addAll((Collection)set, options);
      }

      return newByteChannel(path, (Set)set);
   }

   public static DirectoryStream<Path> newDirectoryStream(Path dir) throws IOException {
      return provider(dir).newDirectoryStream(dir, AcceptAllFilter.FILTER);
   }

   public static DirectoryStream<Path> newDirectoryStream(Path dir, String glob) throws IOException {
      if (glob.equals("*")) {
         return newDirectoryStream(dir);
      } else {
         FileSystem fs = dir.getFileSystem();
         PathMatcher matcher = fs.getPathMatcher("glob:" + glob);
         Filter<Path> filter = new 1(matcher);
         return fs.provider().newDirectoryStream(dir, filter);
      }
   }

   public static DirectoryStream<Path> newDirectoryStream(Path dir, Filter<? super Path> filter) throws IOException {
      return provider(dir).newDirectoryStream(dir, filter);
   }

   public static Path createFile(Path path, FileAttribute... attrs) throws IOException {
      newByteChannel(path, DEFAULT_CREATE_OPTIONS, attrs).close();
      return path;
   }

   public static Path createDirectory(Path dir, FileAttribute... attrs) throws IOException {
      provider(dir).createDirectory(dir, attrs);
      return dir;
   }

   public static Path createDirectories(Path dir, FileAttribute... attrs) throws IOException {
      try {
         createAndCheckIsDirectory(dir, attrs);
         return dir;
      } catch (FileAlreadyExistsException var10) {
         throw var10;
      } catch (IOException var11) {
         SecurityException se = null;
         Path absDir = dir;

         try {
            absDir = dir.toAbsolutePath();
         } catch (SecurityException var8) {
            se = var8;
         }

         Path parent = absDir.getParent();

         while(parent != null) {
            try {
               provider(parent).checkAccess(parent, new AccessMode[0]);
               break;
            } catch (NoSuchFileException var9) {
               parent = parent.getParent();
            }
         }

         if (parent == null) {
            if (se == null) {
               throw new FileSystemException(absDir.toString(), (String)null, "Unable to determine if root directory exists");
            } else {
               throw se;
            }
         } else {
            Path child = parent;
            Iterator var6 = parent.relativize(absDir).iterator();

            while(var6.hasNext()) {
               Path name = (Path)var6.next();
               child = child.resolve(name);
               createAndCheckIsDirectory(child, attrs);
            }

            return dir;
         }
      }
   }

   private static void createAndCheckIsDirectory(Path dir, FileAttribute... attrs) throws IOException {
      try {
         createDirectory(dir, attrs);
      } catch (FileAlreadyExistsException var3) {
         if (!isDirectory(dir)) {
            throw var3;
         }
      }

   }

   public static Path createTempFile(Path dir, String prefix, String suffix, FileAttribute... attrs) throws IOException {
      return TempFileHelper.createTempFile((Path)Objects.requireNonNull(dir), prefix, suffix, attrs);
   }

   public static Path createTempFile(String prefix, String suffix, FileAttribute... attrs) throws IOException {
      return TempFileHelper.createTempFile((Path)null, prefix, suffix, attrs);
   }

   public static Path createTempDirectory(Path dir, String prefix, FileAttribute... attrs) throws IOException {
      return TempFileHelper.createTempDirectory((Path)Objects.requireNonNull(dir), prefix, attrs);
   }

   public static Path createTempDirectory(String prefix, FileAttribute... attrs) throws IOException {
      return TempFileHelper.createTempDirectory((Path)null, prefix, attrs);
   }

   public static Path createSymbolicLink(Path link, Path target, FileAttribute... attrs) throws IOException {
      provider(link).createSymbolicLink(link, target, attrs);
      return link;
   }

   public static Path createLink(Path link, Path existing) throws IOException {
      provider(link).createLink(link, existing);
      return link;
   }

   public static void delete(Path path) throws IOException {
      provider(path).delete(path);
   }

   public static boolean deleteIfExists(Path path) throws IOException {
      return provider(path).deleteIfExists(path);
   }

   public static Path copy(Path source, Path target, CopyOption... options) throws IOException {
      FileSystemProvider provider = provider(source);
      if (provider(target) == provider) {
         provider.copy(source, target, options);
      } else {
         CopyMoveHelper.copyToForeignTarget(source, target, options);
      }

      return target;
   }

   public static Path move(Path source, Path target, CopyOption... options) throws IOException {
      FileSystemProvider provider = provider(source);
      if (provider(target) == provider) {
         provider.move(source, target, options);
      } else {
         CopyMoveHelper.moveToForeignTarget(source, target, options);
      }

      return target;
   }

   public static Path readSymbolicLink(Path link) throws IOException {
      return provider(link).readSymbolicLink(link);
   }

   public static FileStore getFileStore(Path path) throws IOException {
      return provider(path).getFileStore(path);
   }

   public static boolean isSameFile(Path path, Path path2) throws IOException {
      return provider(path).isSameFile(path, path2);
   }

   public static long mismatch(Path path, Path path2) throws IOException {
      if (isSameFile(path, path2)) {
         return -1L;
      } else {
         byte[] buffer1 = new byte[8192];
         byte[] buffer2 = new byte[8192];
         InputStream in1 = newInputStream(path);

         long var11;
         label83: {
            try {
               InputStream in2;
               label85: {
                  in2 = newInputStream(path2);

                  try {
                     long totalRead = 0L;

                     while(true) {
                        int nRead1 = in1.readNBytes(buffer1, 0, 8192);
                        int nRead2 = in2.readNBytes(buffer2, 0, 8192);
                        int i = Arrays.mismatch(buffer1, 0, nRead1, buffer2, 0, nRead2);
                        if (i > -1) {
                           var11 = totalRead + (long)i;
                           break label85;
                        }

                        if (nRead1 < 8192) {
                           var11 = -1L;
                           break;
                        }

                        totalRead += (long)nRead1;
                     }
                  } catch (Throwable var15) {
                     if (in2 != null) {
                        try {
                           in2.close();
                        } catch (Throwable var14) {
                           var15.addSuppressed(var14);
                        }
                     }

                     throw var15;
                  }

                  if (in2 != null) {
                     in2.close();
                  }
                  break label83;
               }

               if (in2 != null) {
                  in2.close();
               }
            } catch (Throwable var16) {
               if (in1 != null) {
                  try {
                     in1.close();
                  } catch (Throwable var13) {
                     var16.addSuppressed(var13);
                  }
               }

               throw var16;
            }

            if (in1 != null) {
               in1.close();
            }

            return var11;
         }

         if (in1 != null) {
            in1.close();
         }

         return var11;
      }
   }

   public static boolean isHidden(Path path) throws IOException {
      return provider(path).isHidden(path);
   }

   public static String probeContentType(Path path) throws IOException {
      Iterator var1 = FileTypeDetectors.installedDetectors.iterator();

      String result;
      do {
         if (!var1.hasNext()) {
            return FileTypeDetectors.defaultFileTypeDetector.probeContentType(path);
         }

         FileTypeDetector detector = (FileTypeDetector)var1.next();
         result = detector.probeContentType(path);
      } while(result == null);

      return result;
   }

   public static <V extends FileAttributeView> V getFileAttributeView(Path path, Class<V> type, LinkOption... options) {
      return provider(path).getFileAttributeView(path, type, options);
   }

   public static <A extends BasicFileAttributes> A readAttributes(Path path, Class<A> type, LinkOption... options) throws IOException {
      return provider(path).readAttributes(path, type, options);
   }

   public static Path setAttribute(Path path, String attribute, Object value, LinkOption... options) throws IOException {
      provider(path).setAttribute(path, attribute, value, options);
      return path;
   }

   public static Object getAttribute(Path path, String attribute, LinkOption... options) throws IOException {
      if (attribute.indexOf(42) < 0 && attribute.indexOf(44) < 0) {
         Map<String, Object> map = readAttributes(path, attribute, options);

         assert map.size() == 1;

         int pos = attribute.indexOf(58);
         String name;
         if (pos == -1) {
            name = attribute;
         } else {
            name = pos == attribute.length() ? "" : attribute.substring(pos + 1);
         }

         return map.get(name);
      } else {
         throw new IllegalArgumentException(attribute);
      }
   }

   public static Map<String, Object> readAttributes(Path path, String attributes, LinkOption... options) throws IOException {
      return provider(path).readAttributes(path, attributes, options);
   }

   public static Set<PosixFilePermission> getPosixFilePermissions(Path path, LinkOption... options) throws IOException {
      return ((PosixFileAttributes)readAttributes(path, PosixFileAttributes.class, options)).permissions();
   }

   public static Path setPosixFilePermissions(Path path, Set<PosixFilePermission> perms) throws IOException {
      PosixFileAttributeView view = (PosixFileAttributeView)getFileAttributeView(path, PosixFileAttributeView.class);
      if (view == null) {
         throw new UnsupportedOperationException();
      } else {
         view.setPermissions(perms);
         return path;
      }
   }

   public static UserPrincipal getOwner(Path path, LinkOption... options) throws IOException {
      FileOwnerAttributeView view = (FileOwnerAttributeView)getFileAttributeView(path, FileOwnerAttributeView.class, options);
      if (view == null) {
         throw new UnsupportedOperationException();
      } else {
         return view.getOwner();
      }
   }

   public static Path setOwner(Path path, UserPrincipal owner) throws IOException {
      FileOwnerAttributeView view = (FileOwnerAttributeView)getFileAttributeView(path, FileOwnerAttributeView.class);
      if (view == null) {
         throw new UnsupportedOperationException();
      } else {
         view.setOwner(owner);
         return path;
      }
   }

   public static boolean isSymbolicLink(Path path) {
      try {
         return readAttributes(path, BasicFileAttributes.class, LinkOption.NOFOLLOW_LINKS).isSymbolicLink();
      } catch (IOException var2) {
         return false;
      }
   }

   public static boolean isDirectory(Path path, LinkOption... options) {
      try {
         BasicFileAttributes attrs = provider(path).readAttributesIfExists(path, BasicFileAttributes.class, options);
         return attrs != null && attrs.isDirectory();
      } catch (IOException var3) {
         return false;
      }
   }

   public static boolean isRegularFile(Path path, LinkOption... options) {
      try {
         BasicFileAttributes attrs = provider(path).readAttributesIfExists(path, BasicFileAttributes.class, options);
         return attrs != null && attrs.isRegularFile();
      } catch (IOException var3) {
         return false;
      }
   }

   public static FileTime getLastModifiedTime(Path path, LinkOption... options) throws IOException {
      return readAttributes(path, BasicFileAttributes.class, options).lastModifiedTime();
   }

   public static Path setLastModifiedTime(Path path, FileTime time) throws IOException {
      ((BasicFileAttributeView)getFileAttributeView(path, BasicFileAttributeView.class)).setTimes((FileTime)Objects.requireNonNull(time), (FileTime)null, (FileTime)null);
      return path;
   }

   public static long size(Path path) throws IOException {
      return readAttributes(path, BasicFileAttributes.class).size();
   }

   private static boolean followLinks(LinkOption... options) {
      boolean followLinks = true;
      LinkOption[] var2 = options;
      int var3 = options.length;

      for(int var4 = 0; var4 < var3; ++var4) {
         LinkOption opt = var2[var4];
         if (opt != LinkOption.NOFOLLOW_LINKS) {
            if (opt == null) {
               throw new NullPointerException();
            }

            throw new AssertionError("Should not get here");
         }

         followLinks = false;
      }

      return followLinks;
   }

   public static boolean exists(Path path, LinkOption... options) {
      return provider(path).exists(path, options);
   }

   public static boolean notExists(Path path, LinkOption... options) {
      try {
         if (followLinks(options)) {
            provider(path).checkAccess(path, new AccessMode[0]);
         } else {
            readAttributes(path, BasicFileAttributes.class, LinkOption.NOFOLLOW_LINKS);
         }

         return false;
      } catch (NoSuchFileException var3) {
         return true;
      } catch (IOException var4) {
         return false;
      }
   }

   private static boolean isAccessible(Path path, AccessMode... modes) {
      try {
         provider(path).checkAccess(path, modes);
         return true;
      } catch (IOException var3) {
         return false;
      }
   }

   public static boolean isReadable(Path path) {
      FileSystemProvider provider = provider(path);
      if (provider instanceof AbstractFileSystemProvider) {
         AbstractFileSystemProvider afsp = (AbstractFileSystemProvider)provider;
         return afsp.isReadable(path);
      } else {
         return isAccessible(path, AccessMode.READ);
      }
   }

   public static boolean isWritable(Path path) {
      FileSystemProvider provider = provider(path);
      if (provider instanceof AbstractFileSystemProvider) {
         AbstractFileSystemProvider afsp = (AbstractFileSystemProvider)provider;
         return afsp.isWritable(path);
      } else {
         return isAccessible(path, AccessMode.WRITE);
      }
   }

   public static boolean isExecutable(Path path) {
      FileSystemProvider provider = provider(path);
      if (provider instanceof AbstractFileSystemProvider) {
         AbstractFileSystemProvider afsp = (AbstractFileSystemProvider)provider;
         return afsp.isExecutable(path);
      } else {
         return isAccessible(path, AccessMode.EXECUTE);
      }
   }

   public static Path walkFileTree(Path start, Set<FileVisitOption> options, int maxDepth, FileVisitor<? super Path> visitor) throws IOException {
      FileTreeWalker walker = new FileTreeWalker(options, maxDepth);

      try {
         Event ev = walker.walk(start);

         do {
            FileVisitResult var10000;
            FileVisitResult res;
            switch(3.$SwitchMap$java$nio$file$FileTreeWalker$EventType[ev.type().ordinal()]) {
            case 1:
               IOException ioe = ev.ioeException();
               if (ioe == null) {
                  assert ev.attributes() != null;

                  var10000 = visitor.visitFile(ev.file(), ev.attributes());
               } else {
                  var10000 = visitor.visitFileFailed(ev.file(), ioe);
               }
               break;
            case 2:
               res = visitor.preVisitDirectory(ev.file(), ev.attributes());
               if (res == FileVisitResult.SKIP_SUBTREE || res == FileVisitResult.SKIP_SIBLINGS) {
                  walker.pop();
               }

               var10000 = res;
               break;
            case 3:
               res = visitor.postVisitDirectory(ev.file(), ev.ioeException());
               if (res == FileVisitResult.SKIP_SIBLINGS) {
                  res = FileVisitResult.CONTINUE;
               }

               var10000 = res;
               break;
            default:
               throw new AssertionError("Should not get here");
            }

            FileVisitResult result = var10000;
            if (Objects.requireNonNull(result) != FileVisitResult.CONTINUE) {
               if (result == FileVisitResult.TERMINATE) {
                  break;
               }

               if (result == FileVisitResult.SKIP_SIBLINGS) {
                  walker.skipRemainingSiblings();
               }
            }

            ev = walker.next();
         } while(ev != null);
      } catch (Throwable var9) {
         try {
            walker.close();
         } catch (Throwable var8) {
            var9.addSuppressed(var8);
         }

         throw var9;
      }

      walker.close();
      return start;
   }

   public static Path walkFileTree(Path start, FileVisitor<? super Path> visitor) throws IOException {
      return walkFileTree(start, EnumSet.noneOf(FileVisitOption.class), Integer.MAX_VALUE, visitor);
   }

   public static BufferedReader newBufferedReader(Path path, Charset cs) throws IOException {
      CharsetDecoder decoder = cs.newDecoder();
      Reader reader = new InputStreamReader(newInputStream(path), decoder);
      return new BufferedReader(reader);
   }

   public static BufferedReader newBufferedReader(Path path) throws IOException {
      return newBufferedReader(path, UTF_8.INSTANCE);
   }

   public static BufferedWriter newBufferedWriter(Path path, Charset cs, OpenOption... options) throws IOException {
      CharsetEncoder encoder = cs.newEncoder();
      Writer writer = new OutputStreamWriter(newOutputStream(path, options), encoder);
      return new BufferedWriter(writer);
   }

   public static BufferedWriter newBufferedWriter(Path path, OpenOption... options) throws IOException {
      return newBufferedWriter(path, UTF_8.INSTANCE, options);
   }

   public static long copy(InputStream in, Path target, CopyOption... options) throws IOException {
      Objects.requireNonNull(in);
      boolean replaceExisting = false;
      CopyOption[] var4 = options;
      int var5 = options.length;

      for(int var6 = 0; var6 < var5; ++var6) {
         CopyOption opt = var4[var6];
         if (opt != StandardCopyOption.REPLACE_EXISTING) {
            if (opt == null) {
               throw new NullPointerException("options contains 'null'");
            }

            throw new UnsupportedOperationException(opt + " not supported");
         }

         replaceExisting = true;
      }

      SecurityException se = null;
      if (replaceExisting) {
         try {
            deleteIfExists(target);
         } catch (SecurityException var10) {
            se = var10;
         }
      }

      OutputStream ostream;
      try {
         ostream = newOutputStream(target, StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE);
      } catch (FileAlreadyExistsException var11) {
         if (se != null) {
            throw se;
         }

         throw var11;
      }

      OutputStream out = ostream;

      long var16;
      try {
         var16 = in.transferTo(out);
      } catch (Throwable var12) {
         if (ostream != null) {
            try {
               out.close();
            } catch (Throwable var9) {
               var12.addSuppressed(var9);
            }
         }

         throw var12;
      }

      if (ostream != null) {
         ostream.close();
      }

      return var16;
   }

   public static long copy(Path source, OutputStream out) throws IOException {
      Objects.requireNonNull(out);
      InputStream in = newInputStream(source);

      long var3;
      try {
         var3 = in.transferTo(out);
      } catch (Throwable var6) {
         if (in != null) {
            try {
               in.close();
            } catch (Throwable var5) {
               var6.addSuppressed(var5);
            }
         }

         throw var6;
      }

      if (in != null) {
         in.close();
      }

      return var3;
   }

   private static byte[] read(InputStream source, int initialSize) throws IOException {
      int capacity = initialSize;
      byte[] buf = new byte[initialSize];
      int nread = 0;

      while(true) {
         int n;
         while((n = source.read(buf, nread, capacity - nread)) > 0) {
            nread += n;
         }

         if (n < 0 || (n = source.read()) < 0) {
            return capacity == nread ? buf : Arrays.copyOf(buf, nread);
         }

         capacity = Math.max(ArraysSupport.newLength(capacity, 1, capacity), 8192);
         buf = Arrays.copyOf(buf, capacity);
         buf[nread++] = (byte)n;
      }
   }

   public static byte[] readAllBytes(Path path) throws IOException {
      SeekableByteChannel sbc = newByteChannel(path);

      byte[] var5;
      try {
         InputStream in = Channels.newInputStream(sbc);

         try {
            if (sbc instanceof FileChannelImpl) {
               ((FileChannelImpl)sbc).setUninterruptible();
            }

            long size = sbc.size();
            if (size > 2147483647L) {
               throw new OutOfMemoryError("Required array size too large");
            }

            var5 = read(in, (int)size);
         } catch (Throwable var8) {
            if (in != null) {
               try {
                  in.close();
               } catch (Throwable var7) {
                  var8.addSuppressed(var7);
               }
            }

            throw var8;
         }

         if (in != null) {
            in.close();
         }
      } catch (Throwable var9) {
         if (sbc != null) {
            try {
               sbc.close();
            } catch (Throwable var6) {
               var9.addSuppressed(var6);
            }
         }

         throw var9;
      }

      if (sbc != null) {
         sbc.close();
      }

      return var5;
   }

   public static String readString(Path path) throws IOException {
      return readString(path, UTF_8.INSTANCE);
   }

   public static String readString(Path path, Charset cs) throws IOException {
      Objects.requireNonNull(path);
      Objects.requireNonNull(cs);
      byte[] ba = readAllBytes(path);
      if (path.getClass().getModule() != Object.class.getModule()) {
         ba = (byte[])ba.clone();
      }

      return JLA.newStringNoRepl(ba, cs);
   }

   public static List<String> readAllLines(Path path, Charset cs) throws IOException {
      BufferedReader reader = newBufferedReader(path, cs);

      ArrayList var7;
      try {
         ArrayList result = new ArrayList();

         while(true) {
            String line = reader.readLine();
            if (line == null) {
               var7 = result;
               break;
            }

            result.add(line);
         }
      } catch (Throwable var6) {
         if (reader != null) {
            try {
               reader.close();
            } catch (Throwable var5) {
               var6.addSuppressed(var5);
            }
         }

         throw var6;
      }

      if (reader != null) {
         reader.close();
      }

      return var7;
   }

   public static List<String> readAllLines(Path path) throws IOException {
      return readAllLines(path, UTF_8.INSTANCE);
   }

   public static Path write(Path path, byte[] bytes, OpenOption... options) throws IOException {
      Objects.requireNonNull(bytes);
      OutputStream out = newOutputStream(path, options);

      try {
         int len = bytes.length;

         int n;
         for(int rem = len; rem > 0; rem -= n) {
            n = Math.min(rem, 8192);
            out.write(bytes, len - rem, n);
         }
      } catch (Throwable var8) {
         if (out != null) {
            try {
               out.close();
            } catch (Throwable var7) {
               var8.addSuppressed(var7);
            }
         }

         throw var8;
      }

      if (out != null) {
         out.close();
      }

      return path;
   }

   public static Path write(Path path, Iterable<? extends CharSequence> lines, Charset cs, OpenOption... options) throws IOException {
      Objects.requireNonNull(lines);
      CharsetEncoder encoder = cs.newEncoder();
      OutputStream out = newOutputStream(path, options);

      try {
         BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(out, encoder));

         try {
            Iterator var7 = lines.iterator();

            while(var7.hasNext()) {
               CharSequence line = (CharSequence)var7.next();
               writer.append(line);
               writer.newLine();
            }
         } catch (Throwable var11) {
            try {
               writer.close();
            } catch (Throwable var10) {
               var11.addSuppressed(var10);
            }

            throw var11;
         }

         writer.close();
      } catch (Throwable var12) {
         if (out != null) {
            try {
               out.close();
            } catch (Throwable var9) {
               var12.addSuppressed(var9);
            }
         }

         throw var12;
      }

      if (out != null) {
         out.close();
      }

      return path;
   }

   public static Path write(Path path, Iterable<? extends CharSequence> lines, OpenOption... options) throws IOException {
      return write(path, lines, UTF_8.INSTANCE, options);
   }

   public static Path writeString(Path path, CharSequence csq, OpenOption... options) throws IOException {
      return writeString(path, csq, UTF_8.INSTANCE, options);
   }

   public static Path writeString(Path path, CharSequence csq, Charset cs, OpenOption... options) throws IOException {
      Objects.requireNonNull(path);
      Objects.requireNonNull(csq);
      Objects.requireNonNull(cs);
      byte[] bytes = JLA.getBytesNoRepl(String.valueOf(csq), cs);
      if (path.getClass().getModule() != Object.class.getModule()) {
         bytes = (byte[])bytes.clone();
      }

      write(path, bytes, options);
      return path;
   }

   public static Stream<Path> list(Path dir) throws IOException {
      DirectoryStream ds = newDirectoryStream(dir);

      try {
         Iterator<Path> delegate = ds.iterator();
         Iterator<Path> iterator = new 2(delegate);
         Spliterator<Path> spliterator = Spliterators.spliteratorUnknownSize(iterator, 1);
         return (Stream)StreamSupport.stream(spliterator, false).onClose(asUncheckedRunnable(ds));
      } catch (RuntimeException | Error var7) {
         Error e = var7;

         try {
            ds.close();
         } catch (IOException var6) {
            IOException ex = var6;

            try {
               e.addSuppressed(ex);
            } catch (Throwable var5) {
               ;
            }
         }

         throw var7;
      }
   }

   public static Stream<Path> walk(Path param0, int param1, FileVisitOption... param2) throws IOException {
      // $FF: Couldn't be decompiled
   }

   public static Stream<Path> walk(Path start, FileVisitOption... options) throws IOException {
      return walk(start, Integer.MAX_VALUE, options);
   }

   public static Stream<Path> find(Path param0, int param1, BiPredicate<Path, BasicFileAttributes> param2, FileVisitOption... param3) throws IOException {
      // $FF: Couldn't be decompiled
   }

   public static Stream<String> lines(Path path, Charset cs) throws IOException {
      if (path.getFileSystem() == FileSystems.getDefault() && FileChannelLinesSpliterator.SUPPORTED_CHARSETS.contains(cs)) {
         FileChannel fc = FileChannel.open(path, StandardOpenOption.READ);
         Stream<String> fcls = createFileChannelLinesStream(fc, cs);
         if (fcls != null) {
            return fcls;
         }

         fc.close();
      }

      return createBufferedReaderLinesStream(newBufferedReader(path, cs));
   }

   private static Stream<String> createFileChannelLinesStream(FileChannel fc, Charset cs) throws IOException {
      try {
         long length = fc.size();
         if (length > 0L && length <= 2147483647L) {
            FileChannelLinesSpliterator fcls = new FileChannelLinesSpliterator(fc, cs, 0, (int)length);
            return (Stream)((Stream)StreamSupport.stream(fcls, false).onClose(asUncheckedRunnable(fc))).onClose(fcls);
         } else {
            return null;
         }
      } catch (RuntimeException | IOException | Error var7) {
         Error e = var7;

         try {
            fc.close();
         } catch (IOException var6) {
            IOException ex = var6;

            try {
               e.addSuppressed(ex);
            } catch (Throwable var5) {
               ;
            }
         }

         throw var7;
      }
   }

   private static Stream<String> createBufferedReaderLinesStream(BufferedReader br) {
      try {
         return (Stream)br.lines().onClose(asUncheckedRunnable(br));
      } catch (RuntimeException | Error var6) {
         Error e = var6;

         try {
            br.close();
         } catch (IOException var5) {
            IOException ex = var5;

            try {
               e.addSuppressed(ex);
            } catch (Throwable var4) {
               ;
            }
         }

         throw var6;
      }
   }

   public static Stream<String> lines(Path path) throws IOException {
      return lines(path, UTF_8.INSTANCE);
   }

   static {
      DEFAULT_CREATE_OPTIONS = Set.of(StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE);
      JLA = SharedSecrets.getJavaLangAccess();
   }
}
