 // Source code is unavailable, and was generated by the Fernflower decompiler.
package java.lang;

import java.lang.constant.Constable;
import java.lang.constant.ConstantDesc;
import java.lang.invoke.MethodHandles.Lookup;
import java.util.Optional;
import jdk.internal.ValueBased;
import jdk.internal.math.DoubleToDecimal;
import jdk.internal.math.FloatingDecimal;
import jdk.internal.vm.annotation.IntrinsicCandidate;

@ValueBased
public final class Double extends Number implements Comparable<Double>, Constable, ConstantDesc {
   public static final double POSITIVE_INFINITY = POSITIVE_INFINITY;
   public static final double NEGATIVE_INFINITY = NEGATIVE_INFINITY;
   public static final double NaN = NaN;
   public static final double MAX_VALUE = MAX_VALUE;
   public static final double MIN_NORMAL = 2.2250738585072014E-308D;
   public static final double MIN_VALUE = MIN_VALUE;
   public static final int SIZE = 64;
   public static final int PRECISION = 53;
   public static final int MAX_EXPONENT = 1023;
   public static final int MIN_EXPONENT = -1022;
   public static final int BYTES = 8;
   public static final Class<Double> TYPE = Class.getPrimitiveClass("double");
   private final double value;
   private static final long serialVersionUID = -9172774392245257468L;

   public static String toString(double d) {
      return DoubleToDecimal.toString(d);
   }

   public static String toHexString(double d) {
      if (!isFinite(d)) {
         return toString(d);
      } else {
         StringBuilder answer = new StringBuilder(24);
         if (Math.copySign(1.0D, d) == -1.0D) {
            answer.append("-");
         }

         answer.append("0x");
         d = Math.abs(d);
         if (d == 0.0D) {
            answer.append("0.0p0");
         } else {
            boolean subnormal = d < 2.2250738585072014E-308D;
            long signifBits = doubleToLongBits(d) & 4503599627370495L | 1152921504606846976L;
            answer.append(subnormal ? "0." : "1.");
            String signif = Long.toHexString(signifBits).substring(3, 16);
            answer.append(signif.equals("0000000000000") ? "0" : signif.replaceFirst("0{1,12}$", ""));
            answer.append('p');
            answer.append(subnormal ? -1022 : Math.getExponent(d));
         }

         return answer.toString();
      }
   }

   public static Double valueOf(String s) throws NumberFormatException {
      return new Double(parseDouble(s));
   }

   @IntrinsicCandidate
   public static Double valueOf(double d) {
      return new Double(d);
   }

   public static double parseDouble(String s) throws NumberFormatException {
      return FloatingDecimal.parseDouble(s);
   }

   public static boolean isNaN(double v) {
      return v != v;
   }

   @IntrinsicCandidate
   public static boolean isInfinite(double v) {
      return Math.abs(v) > MAX_VALUE;
   }

   @IntrinsicCandidate
   public static boolean isFinite(double d) {
      return Math.abs(d) <= MAX_VALUE;
   }

   /** @deprecated */
   @Deprecated(
      since = "9",
      forRemoval = true
   )
   public Double(double value) {
      this.value = value;
   }

   /** @deprecated */
   @Deprecated(
      since = "9",
      forRemoval = true
   )
   public Double(String s) throws NumberFormatException {
      this.value = parseDouble(s);
   }

   public boolean isNaN() {
      return isNaN(this.value);
   }

   public boolean isInfinite() {
      return isInfinite(this.value);
   }

   public String toString() {
      return toString(this.value);
   }

   public byte byteValue() {
      return (byte)((int)this.value);
   }

   public short shortValue() {
      return (short)((int)this.value);
   }

   public int intValue() {
      return (int)this.value;
   }

   public long longValue() {
      return (long)this.value;
   }

   public float floatValue() {
      return (float)this.value;
   }

   @IntrinsicCandidate
   public double doubleValue() {
      return this.value;
   }

   public int hashCode() {
      return hashCode(this.value);
   }

   public static int hashCode(double value) {
      return Long.hashCode(doubleToLongBits(value));
   }

   public boolean equals(Object obj) {
      return obj instanceof Double && doubleToLongBits(((Double)obj).value) == doubleToLongBits(this.value);
   }

   @IntrinsicCandidate
   public static long doubleToLongBits(double value) {
      return !isNaN(value) ? doubleToRawLongBits(value) : 9221120237041090560L;
   }

   @IntrinsicCandidate
   public static native long doubleToRawLongBits(double var0);

   @IntrinsicCandidate
   public static native double longBitsToDouble(long var0);

   public int compareTo(Double anotherDouble) {
      return compare(this.value, anotherDouble.value);
   }

   public static int compare(double d1, double d2) {
      if (d1 < d2) {
         return -1;
      } else if (d1 > d2) {
         return 1;
      } else {
         long thisBits = doubleToLongBits(d1);
         long anotherBits = doubleToLongBits(d2);
         return thisBits == anotherBits ? 0 : (thisBits < anotherBits ? -1 : 1);
      }
   }

   public static double sum(double a, double b) {
      return a + b;
   }

   public static double max(double a, double b) {
      return Math.max(a, b);
   }

   public static double min(double a, double b) {
      return Math.min(a, b);
   }

   public Optional<Double> describeConstable() {
      return Optional.of(this);
   }

   public Double resolveConstantDesc(Lookup lookup) {
      return this;
   }
}
